# Generated by Django 2.2 on 2021-02-22 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0004_comment_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='msg_to_comment',
        ),
    ]
