# Generated by Django 2.2 on 2021-02-22 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0005_auto_20210222_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='msg_to_comment',
            new_name='msg_comment',
        ),
    ]
