# Generated by Django 2.2 on 2021-02-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0006_auto_20210222_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='msg_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_comments', to='login_app.Message'),
        ),
    ]
