# Generated by Django 2.2 on 2021-02-25 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0012_auto_20210224_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joiner',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joiner', to='login_app.User'),
        ),
    ]
