# Generated by Django 2.2 on 2021-02-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_auto_20210225_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='joiner',
        ),
        migrations.AddField(
            model_name='trip',
            name='joiner',
            field=models.ManyToManyField(default=None, null=True, related_name='joiner', to='login_app.User'),
        ),
    ]
