# Generated by Django 2.2 on 2021-02-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0014_auto_20210225_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='joiner',
            field=models.ManyToManyField(default=None, related_name='joiner', to='login_app.User'),
        ),
    ]
